AUTOMATE_TEXTING_PATH = 'C:/Documents/GitHub/automate_texting/'
LOG_PATH = 'C:/WINDOWS/Temp/'
BASE_DIR = 'C:/Documents/GitHub/'
PATH_TO_WALLPAPERS = ''
CHROME_DATA_PATH = ''
CHROME_BINARY_LOCATION = ''